travis:
  secure:
    BINSTAR_TOKEN: U28KpuV0ctra3vsu8/3Vu5Lo14Ta6YCOE47gdr9rRyfn66JF0wavYBql0og5v4KAyC3DcogMNMV30iDCapPdg2x+EUIYlf2TjjllCFZuL2onehFv/4TLCjDWfmmvO5mXzDYnGM4qEnUPdCZusJmeIcDJkp+t5Qw2EPxstE/CLlwe+ozrVMmB53QhTLJo7MSclxZFl7tYuPU7hDReqQVTbnzXdqxzR9vN/ezov0z0TOx9wm01tZ9T2juVNgGX/+RLLrJ1Y4amIHXdpSSzUDYJK3DMfrKXVBBXyUkaZr0vgh5Ybic3ODXoENhafhZDXu2s/APpjiXS4mOQheE+VVhrK01Lvti8R0w1AmXT10eMZ1Is9Vc6Jlq6sCUVlnswC03XAEGVPWkHQUy2Tf228x+vA5F8ueTOxxYtYo8KW8FdUmKav3P36SFbyh4rq6zVifwkGWb84YihaYahktoAQDVr9CoG0jN/s0GKgwx7ovmVceWdGsARAXu/V3wPetOfyx4Z2+OLM2v5TglFrbv3Sgib5TmmraTw2T2wpPkykws6TYsb4ghnInf95dxDF/8/oMYx7SQC18biizjg3nDnDlm04UmR6PVyX7rMBGmn32xSkjK1V30tvL3Lamed/FeHqIct/nHejFdRJwD30ee/FuZQH0zHR2JemIjXOsw3PsORs2Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
