travis:
  secure:
    BINSTAR_TOKEN: DN8h+C8OUwYTdQFisme8M0C73tlG/yXUoEb8KGSj41jfyOp40t9hkPT9X4gQGxThQA8MzDSq6sY4LsnblzV1A1ZJeyH79VM5PGmldYHcOJr1SdHeTnZlY34T58T4c+uyORRaH+t+++BdCuWsPuKfVVK3J5/aUm82YTn+iWsiQ6Hb0Sn/T6sSm5tEyMXE4p+lv3rP2hbE//n5Q+DQbu/8A9g3lNQb0wRKh9xyPhqqk2B1hZ19WXuHFwgOOofLj8Ta3jPSIdqQXIKSrGVkMUnyNtxc/Ye87qKNd6SeP0+KlPNfePBe6aBd/nuzPSQAufWq68ZII7+JkE8rC6gtS8cfzM2WcWmigBMlRN28ElRObIm5yN7ijC0eBKBSCXv9K5bCrjgsiEZnrwxgfj8BUTIIbik5KVHlTbcTeftNCPdBOpthc7bdsweSAp/w4j5haMKBl4AXF259Mdpck1A+lYmyLi42JACjQHFFelBGIKn+8xOUWfONRoOBzrloUQblm1fE2GNIfBlveAqF/asfKEMj50DzyZWPZlm9SueCB56npVTVKeKcgq6Dp0xguULXzcWhrdfyRsH/Fny8nZsHRmzmEDa1lKhBI9MPF/48Yy12VDxdIgreDedyV+WDZ/yrLpYMqJ6Obd3tlovxao0pzFCOzcwcM4eNVCdgOWzjBZB1zgk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
