travis:
  secure:
    BINSTAR_TOKEN: kx+QWJKfZbR243tB9q6R5L6SnbU7eeIVu0ktqFeCtz0EYI/IrQ1oZAAi3sSDgOeLTBnPO9dQteK8Qe2x8AKSXn1nWuJ83KnzhZ2di1a2eD4nC3yrpDxQgaf7gyLQBJWHRAA8CgODYyPRlS6NfXUP2952PiduFZVGmAn4KNePvIPM4NXHWWd1geRbaa++K/b8r5QL0BC9n1FcK5GTxSyS1TrQjGZqO7UUsrt5uSJqYnbtmN8VZiotLUiBx2QPrq2AwQLdpq2dju/1e64WJnK3Z4fzfIO4SXVX6lF61YwjslANONxzZEEsc6TwWzz2rBk7jPwyIdqphVtzuYpMeo9KXPmFkpx3ghPmdiLkj4xLRePo5GwWjRenyVF9nRmj7gXsYBH9HCi2FliV1Dn8uNW0pFfXQ5WUqsja60PcYUBzEI7DrR8IwPhcJ9M68uWMkBQ/6lvHIm5Kf6ooErzfATaMI70H5VG8tiIY9xatYXOMmWm5WcPCAxH2kEXNtfVgLHCqBlvybGlRToFD3vBvbzzB3ixtKBPLEtpqcPUpTsiWoa9fRCkMtrMvvPESq8J6r/a3lgQ3WVBqCAUriPoZ9MZhks0K3NYOtFFK/Odqj7pQ0Ii9RS6VEx8sj/fMzNgJ/41OgA+w6BWQbHoUxHcRkfRZG4mW7D21DIF2PDbL7NIhg1I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
