travis:
  secure:
    BINSTAR_TOKEN: NxQE7eM0dOBvxaDd5YvE6XI/BVOOCPvtpmbCNqxec8SdV/CX/ALS5wiyggdjq5kd/ZLultnc7T8npzZysff8e4jraIh/6bxzt1vHU7/RhCQHD5TBk+0DgMTFiWIani9pVnqpeY8ObaNPTKcTiXBLMpa6fETCylHO54iOnJwvtfkzJi00dBBBizjppgXoNGqvlLepc3+Y3r+ovMwJFIaricgepPtzcqEvxY4gyLNHz3W6uax3zEo96mSwGDRHjohMK3MXCJW/VRqQv6DmoSsN0i2NP+9MxxpGnI1VKqDnHt9AjkI9lCC/nNzklPGfP8YPOf6y6k7R/1n4490DGr0Y6IjvrENz/vLBI/SZ9kksHmQveq2IyzdcXht1BNWMo+d8mqz/F1DbgSWUZSABINH50wbXHj2ZJb90y5N/nySbzD6dGzemAuQGMySBQ+19MKB5oEbfK/lX8U4FAIJeKHuGleazwButRUb+G9iB+x6hzOT0zX88Xot4VbKBhEJ1z90AZskDVVYmgQKbe7NbNtO4/OJZgCWD+qMvrmlihXN2oR+Mpz7XCuysR4kuSBQM13ODXfdnml+ArfZxfrMT2pSPpttByx8u37Pz7I4VBS+7kRa9k67Ud4t2NHxsxqmJnAte05FGLg3CP9uNhgt/CMRUTFOA0KVjJQo6uxf9Pvp2G8w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
